version: "3"

services:
  auth:
    build:
      context: './auth'
      dockerfile: Dockerfile
    ports:
      - '4002:4002'
  store:
    build:
      context: './store'
      dockerfile: Dockerfile
    ports:
      - '4001:4001'
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - '5672:5672'